version: '3'
services:
  nislab:
    image: node:lts
    command: sleep infinity
    ports:
      - 8080:8080
    volumes:
      - ../:/myapp/nislab:cached
      - /myapp/nislab/node_modules
      - /myapp/nislab/.nuxt
    environment:
      - CHOKIDAR_USEPOLLING=true
