name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - run: echo "${{ secrets.SERVER_KEY }}" > aws_lightsail_key
      - run: chmod 600 ./aws_lightsail_key
      - run: ssh -oStrictHostKeyChecking=no -i ./aws_lightsail_key ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "ls /var/www/html"
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install
      - run: yarn generate
        env:
          NUXT_ENV_CTF_ACCESS_TOKEN: ${{ secrets.NUXT_ENV_CTF_ACCESS_TOKEN }}
          NUXT_ENV_SPACE_ID: ${{ secrets.NUXT_ENV_SPACE_ID }}
      # - uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USERNAME }}
      #     key: ${{ secrets.SERVER_KEY }}
      #     source: 'dist/*'
      #     target: '/var/www/html'
      #     rm: true
      - run: echo "🍏 This job's status is ${{ job.status }}."
