name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install
      - run: yarn generate
        env:
          NUXT_ENV_CTF_ACCESS_TOKEN: ${{ secrets.NUXT_ENV_CTF_ACCESS_TOKEN }}
          NUXT_ENV_SPACE_ID: ${{ secrets.NUXT_ENV_SPACE_ID }}
      - run: tar -zcvf dist.tar.gz dist
      - run: echo "${{ secrets.SERVER_KEY }}" > aws_lightsail_key
      - run: chmod 600 ./aws_lightsail_key
      - run: scp -o StrictHostKeyChecking=no -i ./aws_lightsail_key ./dist.tar.gz ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/var/www/html
      - run: ssh -o StrictHostKeyChecking=no -i ./aws_lightsail_key ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "cd /var/www/html && rm -r dist && tar -zxvf dist.tar.gz && rm dist.tar.gz"
      - uses: act10ns/slack@v1
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#workflows'
        if: always()
      # - run: echo "🍏 This job's status is ${{ job.status }}."
