name: Build and Deploy

on:
  push:
    branches:
      - main
  repository_dispatch:

jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: echo "${{ secrets.SERVER_KEY }}" > aws_lightsail_key

      - run: chmod 600 ./aws_lightsail_key

      - run: ssh -o StrictHostKeyChecking=no -i ./aws_lightsail_key ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "cd /var/www/html/nislab && bash scripts/rebuild.sh"

      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_ICON: https://s3-us-west-2.amazonaws.com/slack-files2/avatars/2021-07-06/2257469713729_06357f0ef4a522dfb049_72.png
          SLACK_USERNAME: NISLAB
          SLACK_MESSAGE: 'NISLAB HP が更新されました！'
